# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kevin Chen
email: k_@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  I am a Security Software Engineer at Google New York.
  My name in Chinese is 陈志杰.
baseurl: "/j"
url: "http://ckev.in" # the base hostname & protocol for your site
linkedin: "https://www.linkedin.com/in/kevinchn"
google_scholar: "https://scholar.google.com/citations?user=Y6ue3dYAAAAJ"
chloe: "http://cgao.me/"

twitter_username: zchn
github_username:  zchn

# Theme settings
theme: jekyll-theme-dinky
google_analytics: UA-41120617-2

# Build settings
markdown: kramdown
