# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kevin Chen
email: k_@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  Just trying to set up Jekyll and see if it works.
  This is a second line
baseurl: "/j"
url: "http://ckev.in" # the base hostname & protocol for your site
twitter_username: zchn
github_username:  zchn
theme: dinky

# Build settings
markdown: kramdown
